### ISSUE TITLE
1 player error

### ISSUE THREAD

**Issue by crazcalm** [tkshill/DomiKnows#2]
If you set the number of players to 1, then you get this error.

mwillock:DomiKnows marcus$ python3 app.py
Traceback (most recent call last):
  File "app.py", line 385, in <module>
    attempt = run()
  File "app.py", line 362, in run
    players = make_players(num_players-1)
  File "app.py", line 84, in make_players
    raise IndexError("Number must be greater than 0")
IndexError: Number must be greater than 0

**Comment by crazcalm** [comment]
To reproduce this issue, you have to have your config set to one player and human player equal to true. If the human player is not set to true, one computer player plays the entire game. No errors...

**Comment by crazcalm** [comment]
Created a pull request with a potential fix. See here (https://github.com/tkshill/DomiKnows/pull/3).
